# Generated by Django 4.0.6 on 2022-08-25 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.CharField(default='', max_length=1000)),
                ('image', models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='profile_image')),
                ('background_Image', models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='background_image')),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], max_length=6, null=True)),
            ],
        ),
    ]
