# Generated by Django 4.0.6 on 2022-08-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='relase_date',
            new_name='release_date',
        ),
    ]
