# Generated by Django 4.0.6 on 2022-08-25 18:32

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
