# Generated by Django 4.0.6 on 2022-08-25 19:13

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_category_alter_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
