# Generated by Django 4.0.6 on 2022-08-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='avarageRating',
            field=models.FloatField(default=0),
        ),
    ]
